# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20180321_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PayeeDate',
            new_name='PayeeData',
        ),
    ]
