# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='is_society',
            field=models.BooleanField(default=False),
        ),
    ]
