# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('hosting', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('max_per_person', models.IntegerField(default=2)),
                ('price', models.DecimalField(decimal_places=2, default=25.0, max_digits=4)),
                ('time_sale_start', models.DateTimeField(blank=True, null=True)),
                ('time_sale_end', models.DateTimeField(blank=True, null=True)),
                ('number_tickets_on_sale', models.IntegerField(default=0)),
                ('sales_total', models.IntegerField(default=0)),
                ('tickets_sold', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=events.models.upload_image_path)),
                ('collegeOnSalleTo', models.CharField(choices=[('SEFS', 'SEFS'), ('Medicine', 'Medicine'), ('Business And Law', 'Business And Law'), ('Arts', 'Arts'), ('All', 'All')], default='SEFS', max_length=20)),
            ],
        ),
    ]
