# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sales_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='tickets_sold',
            field=models.IntegerField(default=0),
        ),
    ]
