# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180308_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=4),
        ),
    ]
