# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180313_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='collegeOnSalleTo',
            field=models.CharField(choices=[('SEFS', 'SEFS'), ('Medicine', 'Medicine'), ('Business And Law', 'Business And Law'), ('arts', 'Arts'), ('all', 'All')], default='SEFS', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.upload_image_path),
        ),
    ]
