# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20180313_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='collegeOnSalleTo',
            field=models.CharField(choices=[('SEFS', 'SEFS'), ('Medicine', 'Medicine'), ('Business And Law', 'Business And Law'), ('Arts', 'Arts'), ('All', 'All')], default='SEFS', max_length=20),
        ),
    ]
