# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20180319_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='number_tickets_on_sale',
            field=models.IntegerField(default=0),
        ),
    ]
