# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 18:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('is_activated', models.BooleanField()),
                ('college', models.CharField(choices=[(b'SEFS', b'SEFS'), (b'Medicine', b'Medicine'), (b'Business And Law', b'Business And Law'), (b'arts', b'Arts')], default=b'SEFS', max_length=20)),
                ('year', models.CharField(max_length=1)),
                ('activation_key', models.CharField(max_length=40, null=True)),
                ('key_expires', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
