# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_activated',
        ),
    ]
