# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-09 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_userprofile_is_activated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Student',
        ),
    ]
