# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180321_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=120),
        ),
    ]
